language: ruby
bundler_args: --without development
rvm:
  - 2.7
  - ruby-head
  - jruby-head
matrix:
  allow_failures:
    - rvm: jruby-head
notifications:
  recipients:
    - thibaud@thibaud.me
sudo: false
